# Copyright © 2023, Oracle and/or its affiliates.
# All rights reserved. Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Create Modern data warehousing - a polyglot integration example"
stackDescription: "Deploy the Modern data warehousing - a polyglot integration example Solution"
schemaVersion: 1.1.0
version: "20230803"
locale: "en"
groupings:
  - title: "General Settings"
    visible: true
    variables:
      - tenancy_ocid
      - display_name_prefix
      - region
      - compartment_id
      - show_advanced
  - title: "Autonomous Database Configuration"
    variables:
      - adw_db_name
      - adw_is_free_tier
      - adw_license_model
      - database_admin_password
      - database_wallet_password
      - adw_db_version
      - adw_size_in_tbs
      - adw_enable_auto_scaling
      - adw_cpu_core_count
      - adw_db_workload
  - title: "Oracle Analytics Cloud Configuration"
    variables:
      - analytics_instance_hostname
      - analytics_instance_license_type
      - analytics_instance_feature_set
      - analytics_instance_capacity_value
      - analytics_instance_capacity_capacity_type
      - analytics_instance_network_endpoint_details_network_endpoint_type
      - analytics_instance_idcs_access_token
  - title: "Object Storage"
    variables:
      - bucket_name
      - bucket_access_type
      - bucket_storage_tier
      - bucket_events_enabled
  - title: "Data Catalog"
    variables:
      - datacatalog_display_name
  - title: "Oracle Cloud Infrastructure Data Integration Service"
    variables:
      - odi_display_name
      - odi_description
  - title: "Data Science Optional Configuration"
    variables:
    - project_description
    - project_display_name
    - notebook_session_display_name
    - notebook_session_notebook_session_configuration_details_shape
    - notebook_session_notebook_session_configuration_details_block_storage_size_in_gbs
  - title: "Golden Gate Deployment"
    variables:
    - goden_gate_cpu_core_count
    - goden_gate_deployment_type
    - golden_gate_license_model
    - goden_gate_display_name
    - goden_gate_is_auto_scaling_enabled
    - goden_gate_admin_username
    - goden_gate_admin_password
    - goden_gate_deployment_name
  - title: "Network Configuration"
    variables:
      - vcn_cidr
      - public_subnet_cidr
      - private_subnet_cidr
      - service_name
      - show_advanced_options
  - title: "Hidden Variables"
    visible: false
    variables:
      - user_ocid
      - fingerprint
      - private_key_path
      - use_regional_subnet
      - whitelisted_ips
      - analytics_instance_network_endpoint_details_whitelisted_ips
      - release
# General Configuration Variables
variables:
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy.
    type: string
    required: true
    visible: false
  compartment_id:
    title: Stack Compartment
    description: Choose the compartment where all resources will be provisioned.
    type: oci:identity:compartment:id
    required: true
    visible: true
  region:
    title: Region
    description: Select Region where all resources will be created.
    type: oci:identity:region:name
    required: true
    visible: true
  display_name_prefix:
    title: Display Name Prefix
    type: string
    default: "Deploy the Modern data warehousing - a polyglot integration example Solution"
    description: Enter the Display name for the solution.
    required: true
    visible: true
# Autonomous Database Configuration Variables
  adw_db_name:
    title: Database Name
    description: "Provide Database name. Constraints: 12 alphanumeric characters only. No Spaces."
    required: true
    type: string
    maxLength: 14
  adw_is_free_tier:
    title: Do do want a always Free Oracle Autonomous Database instance?
    description: "Provision Always Free Oracle Autonomous Database instance (1 OCPU 20 GB Storage)?"
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true
  adw_license_model:
    title: "Provision Paid Oracle Autonomous Database instance (2 OCPU 1 TB Storage) - License Included or BYOL?"
    description: "Note: This configuration can be changed later from the OCI console."
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED
    required: true
    visible:
      eq:
        - adw_is_free_tier
        - "false"
  database_admin_password:
    title: Database Admin Password
    description: "Provide admin password. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
    type: password
    required: true
    confirmation: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  database_wallet_password:
    title: Database Wallet Password
    description: Provide database wallet password. Must be a minimum 12 characters, contain at least one uppercase letter, one lowercase letter, one number. Do not include special characters.
    type: password
    required: true
    confirmation: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  adw_db_version:
    title: "A valid Oracle Database version for Autonomous Database"
    description: "A valid Oracle Database version for Autonomous Database"
    type: enum
    enum:
      - "19c"
    default: "19c"
    required: true
    visible: true
  adw_size_in_tbs:
    title: "The quantity of data in the database, in terabytes."
    description: "The quantity of data in the database, in terabytes."
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
      - 128
    default: 1
    visible: true
    required: true
  adw_enable_auto_scaling:
    title: Indicates if auto scaling is enabled for the Autonomous Database CPU core count. 
    description: "Indicates if auto scaling is enabled for the Autonomous Database CPU core count. "
    type: enum
    enum:
      - "true"
      - "false"
    default: "true"
    required: true
    visible: true   
  adw_cpu_core_count:
    title: The number of OCPU cores to be made available to the database 
    description: "The number of OCPU cores to enable. Available cores are subject to your tenancy's service limits."
    type: enum
    enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    default: 1
    required: true
    visible: true
  adw_db_workload:
    title: Autonomous Database Type of workload. 
    description: "Autonomous Database Type of workload."
    type: enum
    enum:
      - "DW"
    default: "DW"
    required: true
    visible: false   
 # Oracle Analytics Cloud Configuration
  analytics_instance_hostname:
    title: Analytics Instance Name
    description: "Enter a unique name for this instance. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "AnalyticsX"
    required: true
    visible: true
  analytics_instance_license_type:
    title: Analytics License
    description: Choose your Oracle Analytics Cloud License Type.
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED
    visible: true
    required: true
  analytics_instance_feature_set:
    title: Analytics Instance Type
    description: Choose the Analytics Product Type.
    type: enum
    enum:
      - SELF_SERVICE_ANALYTICS
      - ENTERPRISE_ANALYTICS
    default: "ENTERPRISE_ANALYTICS"
    visible: create_analytics_instance
    required: true
  analytics_instance_capacity_value:
    title: Analytics Instance Capacity
    description: Provide the number of OCPUs for the Oracle Analytics Instance.
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
    default: 1
    visible: true
    required: true
  analytics_instance_capacity_capacity_type:
    title: Analytics Instance Capacity Type
    description: The capacity value selected (OLPU count, number of users, …etc…). This parameter affects the number of CPUs, amount of memory or other resources allocated to the instance. 
    type: enum
    enum:
      - "OLPU_COUNT"
      - "USERS_COUNT"
    default: "OLPU_COUNT"
    visible: true
    required: true
  analytics_instance_network_endpoint_details_network_endpoint_type:
    title: Analytics Instance Base representation of a network endpoint
    description: "The type of network endpoint: Public or Private Network endpoint" 
    type: enum
    enum:
      - "public"
      - "private"
    default: "public"
    visible: true
    required: true
  analytics_instance_idcs_access_token:
    title: IDCS Access Token
    description: Provide IDCS Access token. See Pre-req section in the Installation Document.
    type: string
    default: "copy-paste your token instead"
    visible: true
    required: true
# Object Storage Configuration  
  bucket_name:
    title: Object Storage Bucket Name
    description: "Enter a unique name for this object storage bucket. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "BucketOne"
    required: true
    visible: true
  bucket_access_type:
    title: Object Storage Access Type
    description: "Select the Access Type of the bucket."
    type: enum
    enum:
      - NoPublicAccess
      - ObjectReadWithoutList
      - ObjectRead
    default: "NoPublicAccess"
    required: true
    visible: true
  bucket_storage_tier:
    title: Object Storage Bucket Name
    description: "Select the storage Tier of the bucket."
    type: enum
    enum:
      - Standard
      - Archive
    default: "Standard"
    required: true
    visible: true
  bucket_events_enabled:
    title: Indicates if bucket events are enabled or not. 
    description: "Indicates if bucket events are enabled or not "
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true  
# Data Catalog Configuration  
  datacatalog_display_name:
    title: Data Catalog Name
    description: "Enter a unique name for this data catalog. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "DataCatalogIP"
    required: true
    visible: true
# ODI - Oracle Cloud Infrastructure Data Integration service
  odi_display_name:
    title: Oracle Data Integration Service
    description: "Enter a unique name for the Oracle Data Integration Service. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "odi_workspace"
    required: true
    visible: true
  odi_description:
    title: Oracle Data Integration Service
    description: "Enter a descriptionfor the Oracle Data Integration Service."
    type: string
    maxLength: 30
    default: "odi_workspace"
    required: true
    visible: true
# Data Science Variables
  project_description:
    type: string
    default: "Machine_learning_platform"
    visible: true
    required: true
    title: "Project Description for Data Science Project"
    description: "Project Description for Data Science Project"
  project_display_name:
    type: string
    default: "Machine_learning_platform"
    visible: true
    required: true
    title: "Project Display Name for Data Science Project"
    description: "Project Display Name for Data Science Project"
  notebook_session_display_name:
    type: string
    default: "Machine_learning_notebook_session"
    visible: true
    required: true
    title: "Notebook Session Display Name for Data Science Project"
    description: "Notebook Session Display Name for Data Science Project"
  notebook_session_notebook_session_configuration_details_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.1
    visible: true
    required: true
    title: "VM Shape for Data Science Project"
    description: "VM Shape for Data Science Project"
    dependsOn:
      compartmentId: compartment_ocid
  notebook_session_notebook_session_configuration_details_block_storage_size_in_gbs:
    type: number
    minimum: 50
    maximum: 1024
    multipleOf: 1
    default: 50
    visible: true
    required: true
    title: "Block Storage Size for Data Science Project"
    description: "Block Storage Size for Data Science Project"
# Golden Gate Deployment Variables
  goden_gate_cpu_core_count:
    title: The number of OCPU cores to be made available to the golden gate deployment 
    description: "The number of OCPU cores to enable. Available cores are subject to your tenancy's service limits."
    type: enum
    enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    default: 2
    required: true
    visible: true
  goden_gate_deployment_type:
    title: Golden Gate deployment Type
    description: Choose your Golden Gate deployment Type.
    type: enum
    enum:
      - OGG
    default: OGG
    required: true
  golden_gate_license_model:
    title: Golden Gate Licence Model
    description: Choose your Golden Gate Licence Model.
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED
    required: true
  goden_gate_display_name:
    type: string
    default: "ogg_deployment"
    visible: true
    required: true
    title: "Golden Gate deployment Display Name"
    description: "Golden Gate deployment Display Name"
  goden_gate_is_auto_scaling_enabled:
    title: Indicates if auto scaling is enabled for the Golgen Date Deployment CPU core count. 
    description: "Allows system to use up to three times the provisioned number of cores as the workload increases up to a maximum of 24 cores."
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true 
  goden_gate_admin_username:
    title: The Admin User for GoldenGate deployment console.
    description: "The GoldenGate deployment console username."
    type: string
    required: true
    default: "ogg"
    visible: true
  goden_gate_admin_password:
    title: The password associated with the GoldenGate deployment console username
    description: "The password associated with the GoldenGate deployment console username. The password must be 8 to 30 characters long and must contain at least 1 uppercase, 1 lowercase, 1 numeric, and 1 special character. Special characters such as ‘$’, ‘^’, or ‘?’ are not allowed."
    type: password
    required: true
    confirmation: true
    default: "Oracle-1234567"
    visible: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  goden_gate_deployment_name:
    type: string
    default: "ogg_deployment"
    visible: true
    required: true
    title: "Golden Gate deployment Name"
    description: "Golden Gate deployment Name"
# Network Configuration
  vcn_cidr:
    visible: 
      and:
        - show_advanced_options
    type: string
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: VCN Network CIDR
    required: true
    description: The CIDR to assign to the new Virtual Cloud Network (VCN) to create for this service. This field is not required if you want to use an existing VCN. When using VCN peering ensure that the VCNs being peered have non-overlapping CIDR blocks.
  public_subnet_cidr:
    visible:
      and:
        - show_advanced_options
    type: string
    default: "10.0.0.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Public Subnet CIDR
    description: "The CIDR of the new public subnet." 
  private_subnet_cidr:
    visible:
      and:
        - show_advanced_options
    type: string
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Private Subnet CIDR
    description: "The CIDR of the new private subnet."
  service_name:
    type: string
    default: "ServiceName"
    visible: true
    required: true
    title: "A prefix for policies and dynamic groups names - scope: to be unique names not duplicates"
    description: "A prefix for policies and dynamic groups names - scope: to be unique names not duplicates"
  show_advanced_options:
    title: Show Advanced Options
    description: Enable advanced options for network.
    type: boolean
    default: false
    visible: true
outputs:
  Instructions:
    type: string
    title: Instructions
  ADW_Service_Console_URL:
    type: link
    title: ADB Service Console URL
  Analytics_URL:
    type: link
    title: Analytics URL
  Buckets:
    type: string
    title: Buckets
  DataCatalog:
    type: string
    title: Data Catalog
  Odi:
    type: string
    title: Odi Workspace
  Datascience:
    type: string
    title: Data Science
  Notebook: 
    type: string
    title: Notebook
  Golgen_gate_console: 
    type: string
    title: Golgen_gate_console
  Deployment_id: 
    type: string
    title: Deployment_id
  Private_ip: 
    type: string
    title: Private_ip
  Deployment_url: 
    type: string
    title: Deployment_url
outputGroups:
  - title: Application
    outputs:
      - Instructions
      - ADW_Service_Console_URL
      - Analytics_URL
      - Buckets
      - DataCatalog
      - Odi
      - Datascience
      - Notebook
      - Golgen_gate_console
      - Deployment_id
      - Private_ip
      - Deployment_url