# Copyright © 2025, Oracle and/or its affiliates.
# All rights reserved. Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Deploy vectorRAG-IN-A-BOX"
stackDescription: "Creates an ADB with vectorRAG-IN-A-BOX generative ai embedded"
schemaVersion: 1.1.0
version: "20230112"
locale: "en"
groupings:
  - title: "General Settings"
    visible: true
    variables:
      - display_name_prefix
      - tenancy_ocid
      - region
      - compartment_id
      - user_ocid
      - fingerprint
  - title: "Autonomous Database Configuration"
    variables:
      - db_name
      - db_is_free_tier
      - db_license_model
      - db_password
      - db_version
      - db_size_in_tbs
      - db_enable_auto_scaling
      - db_compute_model
      - db_compute_count
      - db_workload
      - db_data_safe_status
      - db_operations_insights_status
      - db_database_management_status
  - title: "RAG IN A BOX SETTINGS"
    variables:
      - riab_user
      - riab_password
      - apex_workspace
      - apex_user
      - apex_password
      - bucket_url
      - private_key
  - title: "Object Storage"
    variables:
      - bucket_name
      - bucket_access_type
      - bucket_storage_tier
      - bucket_events_enabled
  - title: "Hidden Variables"
    visible: false
    variables:
      # - user_ocid
      # - fingerprint
      - private_key_path
# General Configuration Variables
variables:
  display_name_prefix:
    title: Display Name Prefix
    type: string
    default: "Oracle vectorRAG-IN-A-BOX solution"
    description: Enter the Display name for the solution.
    required: true
    visible: true
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy.
    type: string
    required: true
    visible: true
  region:
    title: Region
    description: Select Region where all resources will be created.
    type: oci:identity:region:name
    #type: string
    required: true
    visible: true
  user_ocid:
    title: user_ocid
    description: "(user ocid, obtained from OCI console - Profile -> User Settings)"
    type: string
    required: true
    visible: true
  fingerprint:
    title: fingerprint
    description: "(fingerprint obtained after setting up the API public key in OCI console - Profile -> User Settings -> API Keys -> Add Public Key)"
    type: string
    required: true
    visible: true
  compartment_id:
    title: Compartment
    description: Choose the compartment where all resources will be provisioned.
    type: oci:identity:compartment:id 
    # type: string
    required: true
    visible: true
# Autonomous Database Configuration Variables
  db_name:
    title: Database Name
    description: "Provide Database name. Constraints: 12 alphanumeric characters only. No Spaces."
    required: true
    type: string
    maxLength: 30
  db_is_free_tier:
    title: Do do want a always Free Oracle Autonomous Database instance?
    description: "Provision Always Free Oracle Autonomous Database instance (20 GB Storage)?"
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true
  db_license_model:
    title: "Provision Paid Oracle Autonomous Database instance (4 ECPUs 1 TB Storage) - License Included or BYOL?"
    description: "Note: This configuration can be changed later from the OCI console."
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: BRING_YOUR_OWN_LICENSE
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_password:
    title: Database Admin Password
    description: "Provide admin password. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
    type: password
    required: true
    confirmation: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  db_version:
    title: "A valid Oracle Database version for Autonomous Database"
    description: "A valid Oracle Database version for Autonomous Database"
    type: enum
    enum:
      - "23ai"
    default: "23ai"
    required: true
    visible: true
  db_size_in_tbs:
    title: "The quantity of data in the database, in terabytes."
    description: "The quantity of data in the database, in terabytes."
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
      - 128
    default: 1
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_enable_auto_scaling:
    title: Indicates if auto scaling is enabled for the Autonomous Database CPU core count. 
    description: "Indicates if auto scaling is enabled for the Autonomous Database CPU core count. "
    type: enum
    enum:
      - true
      - false
    default: false
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_compute_model:
    title: "The compute model of the Autonomous Database ECPUs"
    description: "The compute model of the Autonomous Database ECPUs"
    type: enum
    enum:
      - "ECPU"
    default: "ECPU"
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_compute_count:
    title: The number of ECPUs cores to be made available to the database 
    description: "The number of ECPU cores to enable. For ECPUs count needs to be minimum 2 and maximum 512 ECPUs"
    type: string
    default: 2
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_workload:
    title: Autonomous Database Type of workload. 
    description: "Autonomous Database Type of workload."
    type: enum
    enum:
      - "DW"
    default: "DW"
    required: true
    visible: false
  db_data_safe_status:
    title: "Status of the Data Safe registration for this Autonomous Database"
    description: "Status of the Data Safe registration for this Autonomous Database. Could be REGISTERED or NOT_REGISTERED."
    type: enum
    enum:
      - "NOT_REGISTERED"
      - "REGISTERED"
    default: "NOT_REGISTERED"
    required: true
    visible: true 
  db_database_management_status:
    title: "Status of Database Management for this Autonomous Database"
    description: "Status of Database Management for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true 
  db_operations_insights_status:
    title: "Status of Operations Insights for this Autonomous Database"
    description: "Status of Operations Insights for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true  
# RAG IN A BOX SETTINGS:
  riab_user:
      title: "The username inside the database where you will install the apex application"
      description: "Provide the username inside the database where you will install the apex application. Constraints: 12 alphanumeric characters only. No Spaces."
      required: true
      type: string
      visible: true
      default: "RIAB"
  riab_password:
      title: "The password for the user inside the database"
      description: "Provide password for the user inside the database. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
      type: password
      required: true
      pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  apex_workspace:
      title: "The name of the apex workspace"
      description: "The name of the apex workspace"
      required: true
      type: string
      visible: true
      default: "RIAB"
  apex_user:
      title: "The user in apex application"
      description: "The user in apex application"
      required: true
      type: string
      visible: true
      default: "ERIAB"
  apex_password:
      title: "The password for the apex user application"
      description: "Provide password for the apex user application. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
      type: password
      required: true
      pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  bucket_url:
      title: "This is the URL of the source bucket where the files will be ingested."
      description: "Provide the URL of the source bucket where the files will be ingested. Example https://objectstorage.us-chicago-1.oraclecloud.com/n/Object_storage_namespace/b/bucket_name/o/. It is optional , if you don't have a bucket already, terraform will create a bucket for you and upload a sampledata file, as you log in the apex you can already put questions about data in industry."
      required: false
      type: string
      visible: true
  private_key:
      title: "Private Key one singleline"
      description: "If never done before, create API Key, download both PRIVATE and PUBLIC key files. Convert PRIVATE KEY into the needed format for the credentials. Enter as single line without breaks in the format -----BEGIN PRIVATE KEY-----.......-----END PRIVATE KEY----- . Use this command to get the key correctly. tr -d '\r\n' <mykeysep_privatepem.pem | pbcopy - and copy the content of it here"
      required: true
      type: string
      visible: true
# Object Storage Configuration  
  bucket_name:
    title: Object Storage Bucket Name
    description: "Enter a unique name for this object storage bucket. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    required: true
    visible: true
  bucket_access_type:
    title: Object Storage Access Type
    description: "Select the Access Type of the bucket."
    type: enum
    enum:
      - NoPublicAccess
      - ObjectReadWithoutList
      - ObjectRead
    default: "ObjectRead"
    required: true
    visible: true
  bucket_storage_tier:
    title: Object Storage Bucket Name
    description: "Select the storage Tier of the bucket."
    type: enum
    enum:
      - Standard
      - Archive
    default: "Standard"
    required: true
    visible: true
  bucket_events_enabled:
    title: Indicates if bucket events are enabled or not. 
    description: "Indicates if bucket events are enabled or not "
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true
outputs:
  ADW_Database_db_connection:
    type: string
    title: ADW_Database_db_connection
    visible: true
  Database_Actions:
    type: link
    title: url
    visible: true
  apex_url:
    type: link
    title: apex_url
    visible: true    
  vectorRAG_IN_A_BOX_URL:
    type: link
    title: select_ai_demo_url
    visible: true      
  adb_admin_password:
    type: string
    title: adb_admin_password
    visible: false      
  adb_user_name:
    type: string
    title: adb_user_name
    visible: true      
  adb_user_password:
    type: string
    title: adb_user_password
    visible: true
  Buckets:
    type: string
    title: Buckets
    visible: true             
outputGroups:
  - title: Database details
    outputs:
      - ADW_Database_db_connection
  - title: ADB user details
    outputs: 
      - Database_Actions
      - apex_url
      - adb_user_name
      - adb_user_password
      - adb_admin_password
      - vectorRAG_IN_A_BOX_URL
      - Buckets

