# Copyright © 2023, Oracle and/or its affiliates.
# All rights reserved. Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Deploy GoldenGate Stream Analytics for production workloads"
stackDescription: "Deploy GoldenGate Stream Analytics for production workloads"
schemaVersion: 1.1.0
version: "20230803"
locale: "en"
groupings:
  - title: "General Settings"
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
  - title: Required Configuration
    visible: true  
    variables:
      - display_name_prefix
      - region
      - compartment_id
  - title: "Autonomous Database Configuration"
    variables:
      - db_name
      - db_is_free_tier
      - db_license_model
      - db_password
      - db_version
      - db_size_in_tbs
      - db_enable_auto_scaling
      - db_compute_model
      - db_compute_count
      - db_workload
      - db_data_safe_status
      - db_operations_insights_status
      - db_database_management_status
  - title: "Oracle Analytics Cloud Configuration"
    variables:
      - analytics_instance_hostname
      - analytics_instance_license_type
      - analytics_instance_feature_set
      - analytics_instance_capacity_value
      - analytics_instance_capacity_capacity_type
      - analytics_instance_network_endpoint_details_network_endpoint_type
      - analytics_instance_idcs_access_token
  - title: "Object Storage"
    variables:
      - bucket_name
      - bucket_access_type
      - bucket_storage_tier
      - bucket_events_enabled
  - title: "Data Catalog"
    variables:
      - datacatalog_display_name
  - title: "Web-Tier-and-Bastion Instance Configuration"
    variables:
      - bastion_shape
  - title: "Workers Instances Configuration"
    variables:
      - worker1_shape
      - worker2_shape
      - worker3_shape
  - title: "Masters Instances Configuration"
    variables:
      - master1_shape
      - master2_shape
  - title: "Network Configuration"
    variables:
      - vcn_cidr
      - public_subnet_cidr
      - private_subnet_cidr
      - show_advanced_options
  - title: "Hidden Variables"
    visible: false
    variables:
      - whitelisted_ips
      - analytics_instance_network_endpoint_details_whitelisted_ips
      - use_regional_subnet
      - release
      - user_ocid
      - fingerprint
      - private_key_path
# General Configuration Variables
variables:
  tenancy_ocid:
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy.
    type: string
    required: true
    visible: false
  compartment_id:
    title: Stack Compartment
    description: Choose the compartment where all resources will be provisioned.
    type: oci:identity:compartment:id
    required: true
    visible: true
  compartment_ocid:
    title: Stack Compartment
    description: Choose the compartment where all resources will be provisioned.
    type: oci:identity:compartment:id
    required: true
    visible: true
  region:
    title: Region
    description: Select Region where all resources will be created.
    type: oci:identity:region:name
    required: true
    visible: true
  display_name_prefix:
    title: Display Name Prefix
    type: string
    default: "Deploy GoldenGate Stream Analytics for production workloads"
    description: Enter the Display name for the solution.
    required: true
    visible: true
# Autonomous Database Configuration Variables
  db_name:
    title: Database Name
    description: "Provide Database name. Constraints: 12 alphanumeric characters only. No Spaces."
    required: true
    type: string
    maxLength: 30
  db_is_free_tier:
    title: Do do want a always Free Oracle Autonomous Database instance?
    description: "Provision Always Free Oracle Autonomous Database instance (1 OCPU 20 GB Storage)?"
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true
  db_license_model:
    title: "Provision Paid Oracle Autonomous Database instance (2 OCPU 1 TB Storage) - License Included or BYOL?"
    description: "Note: This configuration can be changed later from the OCI console."
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: BRING_YOUR_OWN_LICENSE
    required: true
    visible:
      eq:
        - db_is_free_tier
        - "false"
  db_password:
    title: Database Admin Password
    description: "Provide admin password. Constraints: 12 - 30 characters. At least one uppercase letter, one lowercase letter, and one number. No special characters."
    type: password
    required: true
    confirmation: true
    pattern: ((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*[%!@^&)(]).{12,20})
  db_version:
    title: "A valid Oracle Database version for Autonomous Database"
    description: "A valid Oracle Database version for Autonomous Database"
    type: enum
    enum:
      - "19c"
    default: "19c"
    required: true
    visible: true
  db_size_in_tbs:
    title: "The quantity of data in the database, in terabytes."
    description: "The quantity of data in the database, in terabytes."
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
      - 128
    default: 1
    visible: true
    required: true
  db_enable_auto_scaling:
    title: Indicates if auto scaling is enabled for the Autonomous Database CPU core count. 
    description: "Indicates if auto scaling is enabled for the Autonomous Database CPU core count. "
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true   
  db_compute_model:
    title: "The compute model of the Autonomous Database ECPUs"
    description: "The compute model of the Autonomous Database ECPUs"
    type: enum
    enum:
      - "ECPU"
    default: "ECPU"
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_compute_count:
    title: The number of ECPUs cores to be made available to the database 
    description: "The number of ECPU cores to enable. For ECPUs count needs to be minimum 2 and maximum 512 ECPUs"
    type: string
    default: 4
    required: true
    visible:
      eq:
        - db_is_free_tier
        - false
  db_workload:
    title: Autonomous Database Type of workload. 
    description: "Autonomous Database Type of workload."
    type: enum
    enum:
      - "DW"
    default: "DW"
    required: true
    visible: false
  db_data_safe_status:
    title: "Status of the Data Safe registration for this Autonomous Database"
    description: "Status of the Data Safe registration for this Autonomous Database. Could be REGISTERED or NOT_REGISTERED."
    type: enum
    enum:
      - "NOT_REGISTERED"
      - "REGISTERED"
    default: "NOT_REGISTERED"
    required: true
    visible: true 
  db_database_management_status:
    title: "Status of Database Management for this Autonomous Database"
    description: "Status of Database Management for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true 
  db_operations_insights_status:
    title: "Status of Operations Insights for this Autonomous Database"
    description: "Status of Operations Insights for this Autonomous Database. Values supported are ENABLED and NOT_ENABLED"
    type: enum
    enum:
      - "NOT_ENABLED"
      - "ENABLED"
    default: "NOT_ENABLED"
    required: true
    visible: true  
 # Oracle Analytics Cloud Configuration
  analytics_instance_hostname:
    title: Analytics Instance Name
    description: "Enter a unique name for this instance. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "AnalyticsX"
    required: true
    visible: true
  analytics_instance_license_type:
    title: Analytics License
    description: Choose your Oracle Analytics Cloud License Type.
    type: enum
    enum:
      - LICENSE_INCLUDED
      - BRING_YOUR_OWN_LICENSE
    default: LICENSE_INCLUDED
    visible: true
    required: true
  analytics_instance_feature_set:
    title: Analytics Instance Type
    description: Choose the Analytics Product Type.
    type: enum
    enum:
      - SELF_SERVICE_ANALYTICS
      - ENTERPRISE_ANALYTICS
    default: "ENTERPRISE_ANALYTICS"
    visible: create_analytics_instance
    required: true
  analytics_instance_capacity_value:
    title: Analytics Instance Capacity
    description: Provide the number of OCPUs for the Oracle Analytics Instance.
    type: enum
    enum:
      - 1
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 16
      - 24
      - 36
      - 52
    default: 1
    visible: true
    required: true
  analytics_instance_capacity_capacity_type:
    title: Analytics Instance Capacity Type
    description: The capacity value selected (OLPU count, number of users, …etc…). This parameter affects the number of CPUs, amount of memory or other resources allocated to the instance. 
    type: enum
    enum:
      - "OLPU_COUNT"
      - "USERS_COUNT"
    default: "OLPU_COUNT"
    visible: true
    required: true
  analytics_instance_network_endpoint_details_network_endpoint_type:
    title: Analytics Instance Base representation of a network endpoint
    description: "The type of network endpoint: Public or Private Network endpoint" 
    type: enum
    enum:
      - "public"
      - "private"
    default: "public"
    visible: true
    required: true
  analytics_instance_idcs_access_token:
    title: IDCS Access Token
    description: Provide IDCS Access token. See Pre-req section in the Installation Document.
    type: string
    default: "copy-paste your token instead"
    visible: true
    required: true
# Object Storage Configuration  
  bucket_name:
    title: Object Storage Bucket Name
    description: "Enter a unique name for this object storage bucket. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "BucketOne"
    required: true
    visible: true
  bucket_access_type:
    title: Object Storage Access Type
    description: "Select the Access Type of the bucket."
    type: enum
    enum:
      - NoPublicAccess
      - ObjectReadWithoutList
      - ObjectRead
    default: "NoPublicAccess"
    required: true
    visible: true
  bucket_storage_tier:
    title: Object Storage Bucket Name
    description: "Select the storage Tier of the bucket."
    type: enum
    enum:
      - Standard
      - Archive
    default: "Standard"
    required: true
    visible: true
  bucket_events_enabled:
    title: Indicates if bucket events are enabled or not. 
    description: "Indicates if bucket events are enabled or not "
    type: enum
    enum:
      - "true"
      - "false"
    default: "false"
    required: true
    visible: true  
# Data Catalog Configuration  
  datacatalog_display_name:
    title: Data Catalog Name
    description: "Enter a unique name for this data catalog. The name provided must start with a letter, contain only alphanumeric characters, no spaces and span up to 30 characters in total."
    type: string
    maxLength: 30
    default: "DataCatalogIP"
    required: true
    visible: true
# "Web-Tier-and-Bastion Instance Configuration"
  bastion_shape:
    title: Provide the shape for the Web-Tier-and-Bastion Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for the Web-Tier-and-Bastion Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
# "Workers Instances Configuration"
  worker1_shape:
    title: Provide the shape for Worker 1 Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for Worker 1 Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
  worker2_shape:
    title: Provide the shape for Worker 2 Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for Worker 2 Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
  worker3_shape:
    title: Provide the shape for Worker 3 Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for Worker 3 Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
# "Masters Instances Configuration"
  master1_shape:
    title: Provide the shape for Master 1 Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for Master 1 Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
  master2_shape:
    title: Provide the shape for Master 2 Instance - Minim shape neede for this solution is VM.Standard2.4
    description: "Provide the shape for Master 2 Instance"
    type: enum
    enum:
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
      - VM.DenseIO2.8
      - VM.DenseIO2.16
      - VM.DenseIO2.24
      - VM.DenseIO2.16
      - VM.DenseIO2.16
      - BM.Standard2.52	
      - BM.Standard.E3.128
      - BM.Standard.E4.128
      - BM.Standard.A1.160
    default: "VM.Standard2.4"
    required: true
    visible: true
# Network Configuration
  vcn_cidr:
    visible: 
      and:
        - show_advanced_options
    type: string
    default: "172.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: VCN Network CIDR
    required: true
    description: The CIDR to assign to the new Virtual Cloud Network (VCN) to create for this service. This field is not required if you want to use an existing VCN. When using VCN peering ensure that the VCNs being peered have non-overlapping CIDR blocks.
  public_subnet_cidr:
    visible:
      and:
        - show_advanced_options
    type: string
    default: "172.0.0.128/27"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Public Subnet CIDR
    description: "The CIDR of the new public subnet."
  private_subnet_cidr:
    visible:
      and:
        - show_advanced_options
    type: string
    default: "172.0.0.32/27"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Private Subnet CIDR
    description: "The CIDR of the new private subnet."
  show_advanced_options:
    title: Show Advanced Options
    description: Enable advanced options for network.
    type: boolean
    default: false
    visible: true
outputs:
  Instructions:
    type: string
    title: INSTRUCTIONS
  OSA_UI:
    type: string
    title: OSA_UI
  Spark_UI:
    type: string
    title: Spark_UI
  ADW_Service_Console_URL:
    type: link
    title: ADB Service Console URL
  ADW_LOGIN:
    type: string
    title: ADW LOGIN DETAILS
  Analytics_URL:
    type: link
    title: Analytics URL
  Buckets:
    type: string
    title: Buckets
  DataCatalog:
    type: string
    title: DataCatalog
  compute_linux_instances:
    type: string
    title: compute_linux_instances
  all_instances:
    type: string
    title: all_instances
  all_private_ips:
    type: string
    title: all_private_ips
  fss_filesystems:
    type: string
    title: all_private_ips
  fss_mount_targets:
    type: string
    title: all_private_ips
outputGroups:
  - title: Application
    outputs:
      - INSTRUCTIONS
      - OSA_UI
      - Spark_UI
      - ADW_Service_Console_URL
      - ADW_LOGIN
      - Analytics_URL
      - Buckets
      - DataCatalog
      - compute_linux_instances
      - all_instances
      - all_private_ips
      - fss_filesystems
      - fss_mount_targets